name: 'Git Package Version Search'
description: 'Git action that searches for a published version of a package'
author: 'dkhunt27'

branding:
  icon: 'arrow-up-circle'
  color: 'blue'

# Define your inputs here.
inputs:
  token:
    description: 'Git token with read:packages access'
    required: true
  org:
    description: 'Git org for the package'
    required: true
  packageName:
    description: 'Name of the package'
    required: true
  packageVersion:
    description: 'Version of the package'
    required: true
  ifExistsErrorDeleteOrNothing:
    description: '"error": throw error if package exist; "delete": delete the package if exist; "nothing": do nothing if package exist'
    required: true
    type: string

# Define your outputs here.
outputs:
  PackageVersionExisted:
    description: 'true/false if package version existed or not'
  PackageVersionDeleted:
    description: 'true/false if package version was deleted or not'

runs:
  using: node20
  main: dist/index.js

