name: 'Git Package Version Search'
description: 'Git action that searches for a published version of a package'
author: 'dkhunt27'

# Define your inputs here.
inputs:
  token:
    description: 'Git token with read:packages access'
    required: true
  org:
    description: 'Git org for the package'
    required: true
  packageName:
    description: 'Name of the package'
    required: true
  packageVersion:
    description: 'Version of the package'
    required: true
  errorIfExists:
    description: 'If package exists, throw error'
    required: true
    type: boolean

# Define your outputs here.
outputs:
  PackageVersionExist:
    description: 'true/false if package version existed or not'

runs:
  using: node20
  main: dist/index.js
